# Generated by Django 4.0.4 on 2022-05-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
