# Generated by Django 4.0.4 on 2022-05-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_user_name_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_subscriber',
            field=models.BooleanField(default=False),
        ),
    ]
