# Generated by Django 4.0.4 on 2022-05-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_cast_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
